version: '3.7'

networks:
  backend-net:

services:
  conversation:
    image: techtalk/conversation:dev
    build:
      context: .
      dockerfile: src/Dockerfile
    networks:
      - backend-net

  redis:
    image: 'redis:5.0.7-alpine'
    networks:
      - backend-net

  integration-test:
    image: techtalk/conversation:test
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - type: bind
        source: C:/tmp
        target: C:/app/TestResults
    depends_on:
      - conversation
      - redis
    networks:
      - backend-net